// resources/js/pages/admin/sales-returns/show.tsx
import PrintInvoice from '@/components/common/print-invoice';
import AppLayout from '@/layouts/app-layout';
import { Link, router } from '@inertiajs/react';
import {
    ArrowLeft,
    Edit,
    Printer,
    RotateCcw,
    Trash2,
    User,
} from 'lucide-react';
import { useEffect } from 'react';
import { toast } from 'sonner';

type Customer = {
    id: number;
    name: string;
    phone: string | null;
    address: string | null;
    total_due: number;
};

type Sale = {
    id: number;
    bill_no: string;
    sale_date: string;
};

type Product = {
    id: number;
    name: string;
    size: string | null;
    pieces_per_bundle: number;
};

type SalesReturnItem = {
    id: number;
    product_id: number;
    bundles: number;
    extra_pieces: number;
    total_pieces: number;
    weight_kg: number;
    rate_per_kg: number;
    sub_total: number;
    product: Product;
};

type CreatedBy = {
    id: number;
    name: string;
};

type SalesReturn = {
    id: number;
    return_no: string;
    return_date: string;
    total_weight: number;
    sub_total: number;
    discount: number;
    grand_total: number;
    note: string | null;
    customer: Customer;
    sale: Sale | null;
    items: SalesReturnItem[];
    created_by: CreatedBy | null;
    created_at: string;
};

type Props = {
    salesReturn: SalesReturn;
    auto_print?: boolean;
};

export default function SalesReturnShow({ salesReturn, auto_print }: Props) {
    const formatCurrency = (amount: number) => {
        return new Intl.NumberFormat('en-BD', {
            style: 'currency',
            currency: 'BDT',
            minimumFractionDigits: 0,
        }).format(amount);
    };

    const formatDate = (dateString: string) => {
        return new Date(dateString).toLocaleDateString('en-BD', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
        });
    };

    const handlePrint = () => {
        window.print();
    };

    const handleDelete = () => {
        if (
            confirm(
                'Are you sure you want to delete this return? This will reverse stock and customer due adjustments.',
            )
        ) {
            router.delete(`/dashboard/sales-returns/${salesReturn.id}`);
        }
    };

    // Auto print when redirected from create
    useEffect(() => {
        if (auto_print) {
            toast.success('Sales return recorded successfully');
            const timer = setTimeout(() => {
                window.print();
            }, 500);
            return () => clearTimeout(timer);
        }
    }, [auto_print]);

    return (
        <AppLayout>
            <div className="invoice-print-area min-h-screen bg-background p-6 print:bg-white print:p-4">
                <div className="mx-auto max-w-4xl print:max-w-full">
                    {/* Header - Hide on print */}
                    <div className="mb-6 flex items-center justify-between print:hidden">
                        <Link
                            href="/dashboard/sales-returns"
                            className="inline-flex items-center gap-2 text-muted-foreground transition hover:text-foreground"
                        >
                            <ArrowLeft className="h-5 w-5" />
                            <span className="font-medium">Back to Returns</span>
                        </Link>
                        <div className="flex items-center gap-2">
                            <Link
                                href={`/dashboard/sales-returns/${salesReturn.id}/edit`}
                                className="inline-flex items-center gap-2 rounded-lg border border-border px-4 py-2 text-sm font-medium text-foreground transition hover:bg-muted"
                            >
                                <Edit className="h-4 w-4" />
                                Edit
                            </Link>
                            <button
                                onClick={handleDelete}
                                className="inline-flex items-center gap-2 rounded-lg border border-red-200 px-4 py-2 text-sm font-medium text-red-600 transition hover:bg-red-50 dark:border-red-900 dark:hover:bg-red-950"
                            >
                                <Trash2 className="h-4 w-4" />
                                Delete
                            </button>
                            <button
                                onClick={handlePrint}
                                className="inline-flex items-center gap-2 rounded-lg bg-foreground px-4 py-2 text-sm font-medium text-background transition hover:bg-foreground/90"
                            >
                                <Printer className="h-4 w-4" />
                                Print
                            </button>
                        </div>
                    </div>

                    {/* Return Card */}
                    <div className="overflow-hidden rounded-xl border border-border bg-card shadow-sm print:border-0 print:shadow-none">
                        {/* Return Header */}
                        <div className="bg-linear-to-r from-red-500 to-red-600 px-6 py-5 print:bg-red-500">
                            <div className="flex items-start justify-between">
                                <div>
                                    <div className="flex items-center gap-3">
                                        <RotateCcw className="h-6 w-6 text-white" />
                                        <h1 className="text-2xl font-bold text-white">
                                            {salesReturn.return_no}
                                        </h1>
                                    </div>
                                    <p className="mt-1 text-red-100">
                                        {formatDate(salesReturn.return_date)}
                                    </p>
                                    {salesReturn.sale && (
                                        <p className="mt-1 text-sm text-red-100">
                                            Against Sale:{' '}
                                            {salesReturn.sale.bill_no}
                                        </p>
                                    )}
                                </div>
                                <div className="text-right">
                                    <p className="text-3xl font-bold text-white">
                                        -
                                        {formatCurrency(
                                            salesReturn.grand_total,
                                        )}
                                    </p>
                                    <p className="text-xs tracking-wide text-red-100 uppercase">
                                        Return Total
                                    </p>
                                </div>
                            </div>
                        </div>

                        {/* Customer Info */}
                        <div className="border-b border-border px-6 py-4">
                            <div className="flex flex-col justify-between gap-4 sm:flex-row">
                                <div className="flex items-start gap-3">
                                    <div className="hidden rounded-full bg-red-100 p-2 sm:flex dark:bg-red-900/30">
                                        <User className="h-5 w-5 text-red-600 dark:text-red-400" />
                                    </div>
                                    <div>
                                        <h3 className="text-xl font-semibold text-foreground">
                                            {salesReturn.customer.name}
                                        </h3>
                                        <p className="text-sm text-muted-foreground">
                                            {salesReturn.customer.address}
                                        </p>
                                        <p className="text-sm text-muted-foreground">
                                            {salesReturn.customer.phone}
                                        </p>
                                    </div>
                                </div>
                                <div className="text-right">
                                    <p className="text-sm text-muted-foreground">
                                        Total Weight
                                    </p>
                                    <p className="text-lg font-semibold text-foreground">
                                        {salesReturn.total_weight} kg
                                    </p>
                                </div>
                            </div>
                        </div>

                        {/* Items Table */}
                        <div className="px-6 py-4">
                            <table className="w-full">
                                <thead>
                                    <tr className="border-b border-border text-left">
                                        <th className="pb-3 text-sm font-medium text-muted-foreground">
                                            Product
                                        </th>
                                        <th className="pb-3 text-center text-sm font-medium text-muted-foreground">
                                            Qty
                                        </th>
                                        <th className="pb-3 text-center text-sm font-medium text-muted-foreground">
                                            Weight
                                        </th>
                                        <th className="pb-3 text-center text-sm font-medium text-muted-foreground">
                                            Rate/kg
                                        </th>
                                        <th className="pb-3 text-right text-sm font-medium text-muted-foreground">
                                            Amount
                                        </th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-border">
                                    {salesReturn.items.map((item) => (
                                        <tr key={item.id}>
                                            <td className="py-3">
                                                <p className="font-medium text-foreground">
                                                    {item.product.name}
                                                </p>
                                                <p className="text-xs text-muted-foreground">
                                                    {item.product.size} •{' '}
                                                    {
                                                        item.product
                                                            .pieces_per_bundle
                                                    }{' '}
                                                    pcs/bdl
                                                </p>
                                            </td>
                                            <td className="py-3 text-center">
                                                <p className="font-medium text-foreground">
                                                    {item.bundles > 0 && (
                                                        <span>
                                                            {item.bundles} bdl
                                                        </span>
                                                    )}
                                                    {item.bundles > 0 &&
                                                        item.extra_pieces >
                                                        0 && (
                                                            <span> + </span>
                                                        )}
                                                    {item.extra_pieces > 0 && (
                                                        <span>
                                                            {item.extra_pieces}{' '}
                                                            pcs
                                                        </span>
                                                    )}
                                                </p>
                                                <p className="text-xs text-muted-foreground">
                                                    {item.total_pieces} pcs
                                                </p>
                                            </td>
                                            <td className="py-3 text-center text-foreground">
                                                {item.weight_kg} kg
                                            </td>
                                            <td className="py-3 text-center text-foreground">
                                                ৳{item.rate_per_kg}
                                            </td>
                                            <td className="py-3 text-right font-medium text-red-600">
                                                {formatCurrency(item.sub_total)}
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>

                        {/* Totals */}
                        <div className="border-t border-border bg-muted/30 px-6 py-4">
                            <div className="flex justify-end">
                                <div className="w-64 space-y-2">
                                    <div className="flex justify-between text-sm">
                                        <span className="text-muted-foreground">
                                            Sub Total
                                        </span>
                                        <span className="font-medium text-foreground">
                                            {formatCurrency(
                                                salesReturn.sub_total,
                                            )}
                                        </span>
                                    </div>
                                    {salesReturn.discount > 0 && (
                                        <div className="flex justify-between text-sm">
                                            <span className="text-muted-foreground">
                                                Discount
                                            </span>
                                            <span className="font-medium text-foreground">
                                                -
                                                {formatCurrency(
                                                    salesReturn.discount,
                                                )}
                                            </span>
                                        </div>
                                    )}
                                    <div className="flex justify-between border-t pt-2 text-lg font-semibold">
                                        <span>Grand Total</span>
                                        <span className="text-red-600">
                                            -
                                            {formatCurrency(
                                                salesReturn.grand_total,
                                            )}
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Notes & Footer */}
                        {salesReturn.note && (
                            <div className="border-t border-border px-6 py-4">
                                <h4 className="mb-2 text-sm font-medium text-muted-foreground">
                                    Notes
                                </h4>
                                <p className="text-sm text-foreground">
                                    {salesReturn.note}
                                </p>
                            </div>
                        )}

                        <div className="border-t border-border bg-muted/30 px-6 py-3 text-center text-xs text-muted-foreground">
                            <p>
                                Created by{' '}
                                {salesReturn.created_by?.name || 'System'} on{' '}
                                {formatDate(salesReturn.created_at)}
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            {/* Print Layout - Hidden on screen, visible only when printing */}
            <PrintInvoice
                type="return"
                invoiceNo={salesReturn.return_no}
                date={new Date(salesReturn.return_date).toLocaleDateString('en-BD', {
                    day: '2-digit',
                    month: 'short',
                    year: 'numeric',
                })}
                soldBy={salesReturn.created_by?.name || 'Admin'}
                customerName={salesReturn.customer.name}
                customerContact={salesReturn.customer.phone}
                items={salesReturn.items.map((item, index) => ({
                    sl: index + 1,
                    name: `${item.product.name}${item.product.size ? ` (${item.product.size})` : ''}`,
                    rate: item.rate_per_kg,
                    qty: `${item.weight_kg} KG`,
                    total: item.sub_total,
                }))}
                subTotal={salesReturn.sub_total}
                discount={salesReturn.discount}
                grandTotal={salesReturn.grand_total}
                paidTotal={0}
                dueAmount={salesReturn.grand_total}
                customerTotalDue={salesReturn.customer.total_due}
                totalWeight={salesReturn.total_weight}
            />
        </AppLayout>
    );
}

// resources/js/pages/admin/references/Sales/Show.vue
<template>

    <Head :title="sale.bill_no + ' - Lavloss'" />

    <!-- Screen Layout - Responsive -->
    <div class="screen-only tw-mx-auto tw-pb-12 tw-max-w-full tw-px-3 sm:tw-px-4">

        <!-- Top Navigation -->
        <div class="tw-flex tw-items-center tw-justify-between tw-mb-4">
            <Link :href="route('admin.sales.index')"
                class="tw-inline-flex tw-items-center tw-gap-2 tw-text-gray-600 hover:tw-text-gray-900 tw-transition-colors">
            <svg class="tw-w-5 tw-h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
            </svg>
            <span class="tw-font-medium">Back to Sales</span>
            </Link>
            <button type="button" @click="printInvoice"
                class="tw-inline-flex tw-items-center tw-gap-2 tw-bg-gray-900 tw-text-white tw-px-4 tw-py-2 tw-rounded-lg tw-font-medium hover:tw-bg-gray-800 tw-transition-colors tw-shadow-sm">
                <svg class="tw-w-4 tw-h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
                </svg>
                Print
            </button>
        </div>

        <!-- Invoice Card -->
        <div
            class="tw-bg-white tw-min-h-[80vh] tw-shadow-sm tw-rounded-md tw-overflow-hidden tw-border tw-border-gray-100">

            <!-- Header with Status Badge -->
            <div class="tw-bg-gradient-to-r tw-from-emerald-500 tw-to-emerald-600 tw-px-5 tw-py-4">
                <div class="tw-flex tw-flex-row tw-justify-between tw-items-start sm:tw-items-center tw-gap-3">
                    <div>
                        <div class="tw-flex tw-items-center tw-gap-3">
                            <h1 class="tw-text-xl sm:tw-text-2xl tw-font-bold tw-text-white">{{ sale.bill_no }}</h1>
                        </div>
                        <p class="tw-text-emerald-100 tw-text-sm tw-mt-1">{{ sale.sale_date }}</p>
                    </div>
                    <div class="tw-text-left sm:tw-text-right">
                        <p class="tw-text-2xl sm:tw-text-3xl tw-font-bold tw-text-white">৳{{ sale.grand_total }}</p>
                        <p class="tw-text-emerald-100 tw-text-xs tw-uppercase tw-tracking-wide">Grand Total</p>
                    </div>
                </div>
            </div>

            <!-- Customer Info -->
            <div class="tw-px-5 tw-py-4 tw-border-b tw-border-gray-100">
                <div class="tw-flex tw-flex-row tw-gap-4">
                    <!-- Customer Details -->
                    <div class="tw-flex tw-items-start tw-gap-3 tw-flex-1">
                        <div
                            class="tw-w-10 tw-h-10 tw-rounded-full tw-bg-emerald-100 tw-hidden sm:tw-flex tw-items-center tw-justify-center tw-flex-shrink-0">
                            <svg class="tw-w-5 tw-h-5 tw-text-emerald-600" fill="none" stroke="currentColor"
                                viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                            </svg>
                        </div>
                        <div class="tw-min-w-0">
                            <h3 class="tw-text-2xl tw-font-semibold tw-text-gray-900">{{ sale.customer.name }}</h3>
                            <p class="tw-text-sm tw-text-gray-500">{{ sale.customer.address }}</p>
                            <p class="tw-text-sm tw-text-gray-500">{{ sale.customer.phone }}</p>
                        </div>
                    </div>
                    <!-- Customer Due -->
                    <div class="tw-flex-shrink-0 tw-text-left sm:tw-text-right tw-pl-13 sm:tw-pl-0">
                        <p class="tw-text-xs tw-text-gray-400 tw-uppercase tw-tracking-wide">Total Due</p>
                        <p class="tw-text-2xl tw-font-bold"
                            :class="sale.customer.total_due > 0 ? 'tw-text-red-600' : 'tw-text-emerald-600'">
                            ৳{{ sale.customer.total_due }}
                        </p>
                        <p class="tw-text-xs tw-text-gray-400">Overall balance</p>
                    </div>
                </div>
            </div>

            <!-- Items Section -->
            <div class="tw-px-5 tw-py-4">
                <!-- Desktop Table -->
                <div class="tw-hidden sm:tw-block tw-overflow-hidden tw-rounded-lg tw-border tw-border-gray-200">
                    <table class="tw-w-full">
                        <thead>
                            <tr class="tw-bg-gray-50">
                                <th
                                    class="tw-px-4 tw-py-3 tw-text-left tw-text-xs tw-font-semibold tw-text-gray-500 tw-uppercase tw-tracking-wider">
                                    #</th>
                                <th
                                    class="tw-px-4 tw-py-3 tw-text-left tw-text-xs tw-font-semibold tw-text-gray-500 tw-uppercase tw-tracking-wider">
                                    Product</th>
                                <th
                                    class="tw-px-4 tw-py-3 tw-text-right tw-text-xs tw-font-semibold tw-text-gray-500 tw-uppercase tw-tracking-wider">
                                    Rate</th>
                                <th
                                    class="tw-px-4 tw-py-3 tw-text-center tw-text-xs tw-font-semibold tw-text-gray-500 tw-uppercase tw-tracking-wider">
                                    Qty</th>
                                <th
                                    class="tw-px-4 tw-py-3 tw-text-right tw-text-xs tw-font-semibold tw-text-gray-500 tw-uppercase tw-tracking-wider">
                                    Total</th>
                            </tr>
                        </thead>
                        <tbody class="tw-divide-y tw-divide-gray-100">
                            <tr v-for="(item, index) in sale.sale_items" :key="item.id"
                                class="hover:tw-bg-gray-50 tw-transition-colors">
                                <td class="tw-px-4 tw-py-3 tw-text-sm tw-text-gray-400">{{ index + 1 }}</td>
                                <td class="tw-px-4 tw-py-3">
                                    <span class="tw-font-medium tw-text-gray-900">{{ item.title }}</span>
                                </td>
                                <td class="tw-px-4 tw-py-3 tw-text-right tw-text-sm tw-text-gray-600">৳{{
                                    item.unit_price }}</td>
                                <td class="tw-px-4 tw-py-3 tw-text-center">
                                    <span class="tw-inline-flex tw-items-center tw-gap-1 tw-text-sm">
                                        <span class="tw-font-medium tw-text-gray-900">{{ item.quantity }}</span>
                                        <span class="tw-text-gray-400">{{ item.unit }}</span>
                                    </span>
                                </td>
                                <td class="tw-px-4 tw-py-3 tw-text-right tw-font-semibold tw-text-gray-900">৳{{
                                    item.sub_total }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <!-- Mobile Cards -->
                <div class="sm:tw-hidden tw-space-y-2">
                    <div v-for="(item, index) in sale.sale_items" :key="item.id"
                        class="tw-bg-gray-50 tw-rounded-lg tw-p-3 tw-border tw-border-gray-100">
                        <div class="tw-flex tw-justify-between tw-items-start">
                            <div class="tw-flex-1">
                                <p class="tw-font-medium tw-text-gray-900">{{ item.title }}</p>
                                <p class="tw-text-sm tw-text-gray-500 tw-mt-0.5">
                                    ৳{{ item.unit_price }} × {{ item.quantity }} {{ item.unit }}
                                </p>
                            </div>
                            <p class="tw-font-bold tw-text-gray-900">৳{{ item.sub_total }}</p>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Summary Section -->
            <div class="tw-px-5 tw-py-4 tw-bg-gray-50 tw-border-t tw-border-gray-100">
                <div class="tw-flex tw-flex-col sm:tw-flex-row sm:tw-justify-between tw-gap-4">
                    <!-- Note & Amount in Words (Left on desktop) -->
                    <div v-if="sale.sale_note || amountInWords" class="tw-hidden sm:tw-block tw-flex-1">
                        <div class="tw-space-y-3">
                            <div v-if="sale.sale_note">
                                <p class="tw-text-xs tw-font-medium tw-text-gray-400 tw-uppercase">Note</p>
                                <p class="tw-text-sm tw-text-gray-600">{{ sale.sale_note }}</p>
                            </div>
                            <div>
                                <p class="tw-text-xs tw-font-medium tw-text-gray-400 tw-uppercase">In Words</p>
                                <p class="tw-text-sm tw-text-gray-600 tw-capitalize">{{ amountInWords }}</p>
                            </div>
                        </div>
                    </div>
                    <!-- Totals (Right on desktop) -->
                    <div class="tw-w-full sm:tw-w-64 tw-space-y-2">
                        <div class="tw-flex tw-justify-between tw-text-sm">
                            <span class="tw-text-gray-500">Subtotal</span>
                            <span class="tw-text-gray-700">৳{{ sale.sub_total }}</span>
                        </div>
                        <div v-if="sale.discount > 0" class="tw-flex tw-justify-between tw-text-sm">
                            <span class="tw-text-gray-500">Discount</span>
                            <span class="tw-text-emerald-600">-৳{{ sale.discount }}</span>
                        </div>
                        <div v-if="sale.extra_fees > 0" class="tw-flex tw-justify-between tw-text-sm">
                            <span class="tw-text-gray-500">Extra Fees</span>
                            <span class="tw-text-gray-700">+৳{{ sale.extra_fees }}</span>
                        </div>
                        <div class="tw-flex tw-justify-between tw-pt-2 tw-border-t tw-border-gray-200">
                            <span class="tw-font-semibold tw-text-gray-900">Grand Total</span>
                            <span class="tw-font-bold tw-text-lg tw-text-gray-900">৳{{ sale.grand_total }}</span>
                        </div>
                        <div class="tw-flex tw-justify-between tw-text-sm">
                            <span class="tw-text-gray-500">Paid</span>
                            <span class="tw-text-emerald-600 tw-font-medium">৳{{ sale.paid_amount }}</span>
                        </div>
                        <div v-if="sale.due_amount > 0"
                            class="tw-flex tw-justify-between tw-pt-2 tw-border-t tw-border-gray-200">
                            <span class="tw-font-semibold tw-text-red-600">Due</span>
                            <span class="tw-font-bold tw-text-red-600">৳{{ sale.due_amount }}</span>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Note & Amount in Words -->
            <div v-if="sale.sale_note || amountInWords"
                class="tw-px-5 tw-block sm:tw-hidden tw-py-4 tw-border-t tw-border-gray-100">
                <div class="tw-space-y-3">
                    <div v-if="sale.sale_note" class="tw-flex tw-gap-2">
                        <div>
                            <p class="tw-text-xs tw-font-medium tw-text-gray-400 tw-uppercase">Note</p>
                            <p class="tw-text-sm tw-text-gray-600">{{ sale.sale_note }}</p>
                        </div>
                    </div>
                    <div class="tw-flex tw-gap-2">
                        <div>
                            <p class="tw-text-xs tw-font-medium tw-text-gray-400 tw-uppercase">In Words</p>
                            <p class="tw-text-sm tw-text-gray-600 tw-capitalize">{{ amountInWords }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Print Layout - Uses reusable component -->
    <PrintInvoice type="sale" :invoiceNo="sale.bill_no" :invoiceDate="sale.sale_date" :partyName="sale.customer.name"
        :partyAddress="sale.customer.address" :partyPhone="sale.customer.phone" :partyDue="sale.customer.total_due"
        :items="sale.sale_items" :subTotal="sale.sub_total" :discount="sale.discount" :extraFees="sale.extra_fees"
        :grandTotal="sale.grand_total" :paidAmount="sale.paid_amount" :dueAmount="sale.due_amount"
        :note="sale.sale_note" />
</template>

<script setup>
import { Head, Link, usePage } from '@inertiajs/vue3';
import { ref, onMounted, computed } from 'vue';
import { ToWords } from 'to-words';
import PrintInvoice from '@/Components/PrintInvoice.vue';

const toWords = new ToWords({
    localeCode: 'en-BD',
    converterOptions: {
        currency: true,
        ignoreDecimal: true,
    },
});

const props = defineProps({
    sale: Object
});

// Fetching Company information
const page = usePage()
const company = computed(() => page.props.company);

let amountInWords = ref('');

onMounted(() => {
    convertAmountToWords();
});

const convertAmountToWords = () => {
    amountInWords.value = toWords.convert(props.sale.grand_total);
}

const printInvoice = () => {
    window.print();
};
</script>

<style>
/* Hide print component on screen */
@media screen {
    .screen-only {
        display: grid;
    }
}

/* Hide screen layout when printing */
@media print {
    .screen-only {
        display: none !important;
    }
}
</style>
